Parameters:
  TargetHost:
    Type: String
    Description: target database host name
  TargetDb:
    Type: String
    Description: target database db name
  TargetUser:
    Type: String
    Description: target database user name
  TargetPassword:
    Type: String
    Description: target database password
  SourceHost:
    Type: String
    Description: source database host name
  SourceDb:
    Type: String
    Description: source database db name
  SourceUser:
    Type: String
    Description: source database user name
  SourcePassword:
    Type: String
    Description: source database password

Resources:
  MySQLDumpFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: MySQLDump
      Handler: function.handler
      Runtime: provided
      MemorySize: 256 # in MB
      Timeout: 60 # in seconds
      CodeUri: .
      Layers:
        - arn:aws:lambda:ap-southeast-2:xxxx:layer:bash-runtime:1
        - arn:aws:lambda:ap-southeast-2:xxxx:layer:mysql-layer:1
      Environment:
        Variables:
          TARGET_HOST: !Ref TargetHost
          TARGET_DB: !Ref TargetDb
          TARGET_USER: !Ref TargetUser
          TARGET_PASSWORD: !Ref TargetPassword
          SOURCE_HOST: !Ref SourceHost
          SOURCE_DB: !Ref SourceDb
          SOURCE_USER: !Ref SourceUser
          SOURCE_PASSWORD: !Ref SourcePassword
    Metadata:
      BuildMethod: makefile
